Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2019-05, with the labels that each got.

#213 [RHDM-858][RHPAM-1924] Add JDG hotrod security to config in RHDM and RHPAM
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/features/common/clustering.feature
Labels: master ⇨ 7.4.0, ready 🚀

#233 [KIECLOUD-203] add feature to delete cached artifacts via build-overrides.sh
  tools/build-overrides/build-overrides.sh
Labels: 7.3.x ⇨ 7.3.1, ready 🚀

#230 [KIECLOUD-203] add feature to delete cached artifacts via build-overrides.sh
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.4.0, ready 🚀

#236 [BXMSPROD-161] Implement or Connect nightly build to Container image nightly builds
  tools/build-osbs/build-osbs.sh
Labels: 7.3.x ⇨ 7.3.1, ready 🚀

#237 [BXMSPROD-161] Implement or Connect nightly build to Container image nightly builds
  tools/build-osbs/build-osbs.sh
Labels: master ⇨ 7.4.0, ready 🚀

#239 [KIECLOUD-209] add sha512 and no-color options to build-overrides.sh
  tools/build-osbs/build-osbs.sh
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.4.0, ready 🚀

#240 [KIECLOUD-209] add sha512 and no-color options to build-overrides.sh
  tools/build-osbs/build-osbs.sh
  tools/build-overrides/build-overrides.sh
Labels: 7.3.x ⇨ 7.3.1, ready 🚀

#241 [RHDM-721][RHPAM-1488] Add JDG indexing support to OpenShift HA Authoring in RHDM and RHPAM
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
Labels: master ⇨ 7.4.0, ready 🚀

#214 [KIECLOUD-184] RHPAM OpenShiftStartupStrategy Full Release
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
Labels: master ⇨ 7.4.0, ready 🚀

#242 [RHDM-894][RHPAM-2016] Update RHDM and RHPAM images to use RHEL8 (UBI) base layer
  jboss-kie-db-drivers/added/modules/system/layers/openshift/org/mariadb/main/module.xml
  jboss-kie-db-drivers/added/modules/system/layers/openshift/org/postgresql/main/module.xml
  jboss-kie-db-drivers/configure.sh
  jboss-kie-db-drivers/module.yaml
  jboss-kie-jdk-clean/configure.sh
  jboss-kie-jdk-clean/module.yaml
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
  jboss-kie-kieserver/added/launch/kieserver-install.sh
  jboss-kie-kieserver/added/launch/kieserver-pull.sh
  jboss-kie-kieserver/configure.sh
  jboss-kie-smartrouter/configure.sh
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-common.sh
  os.kieserver.launch/added/kieserver-config.sh
  os.kieserver.launch/added/kieserver-install.sh
Labels: master ⇨ 7.4.0, ready 🚀

#245 [KIECLOUD-216] - Fixing eval semicolon problem
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
Labels: master ⇨ 7.4.0, ready 🚀

#246 [KIECLOUD-220] - Fixing delete cache feature for cekit 3.x
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.4.0, ready 🚀

#244 [rhpam-1387] Allow set Smart router location to external URL in RHPAM
  jboss-kie-common/added/launch/jboss-kie-common.sh
  jboss-kie-common/configure.sh
  jboss-kie-common/module.yaml
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-common.sh
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
Labels: master ⇨ 7.4.0, ready 🚀

#247 [KIECLOUD-217] Kie data path standardization
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/configure.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-authoring.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.4.0, ready 🚀

#248 [KIECLOUD-218] disable kieserver ping with OpenShiftStartupStrategy
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/businesscentral/rhpam-businesscentral.feature
Labels: master ⇨ 7.4.0, ready 🚀

#250 [KIECLOUD-218] Logs are constantly flooded with 'Unable to load key store. Using password from configuration'
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-security.sh
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/features/common/kie-workbench-common.feature
Labels: master ⇨ 7.4.0, ready 🚀

#249 [RHPAM-2002] - Some external databases fail when using externaldb tem…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.4.0, ready 🚀

#253 [KIECLOUD-226] - Set RHPAM_NONXA to false on authoring templates
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
Labels: master ⇨ 7.4.0, ready 🚀

#251 [RHPAM-2008] - Logs are constantly flooded with 'Unable to load key…
  jboss-kie-common/added/launch/jboss-kie-common.sh
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-hooks.sh
Labels: master ⇨ 7.4.0, ready 🚀

#254 [KIECLOUD-220] - Update on 3.0.1 cekit compatibility
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.4.0, ready 🚀

#255 [KIECLOUD-208] update 6.4.x artifacts to 6.4.12.GA
  os.kieserver.webapp/configure.sh
Labels: master ⇨ 6.4.12, ready 🚀
