Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2019-11, with the labels that each got.

#330 [KIECLOUD-332] image naming convention changes
  tests/features/common/clustering.feature
  tests/features/common/kie-common.feature
  tests/features/common/kie-controller-common.feature
  tests/features/common/kie-kieserver-common.feature
  tests/features/common/kie-workbench-authoring.feature
  tests/features/common/kie-workbench-common.feature
  tests/features/rhdm/controller/rhdm-controller.feature
  tests/features/rhdm/decisioncentral/rhdm-decisioncentral.feature
  tests/features/rhdm/kieserver/rhdm-kieserver.feature
  tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/businesscentral/rhpam-businesscentral.feature
  tests/features/rhpam/controller/rhpam-controller.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
Labels: master ⇨ 7.6.0, ready 🚀

#331 [KIECLOUD-332] [7.5.x] image naming convention changes
  tests/features/common/clustering.feature
  tests/features/common/kie-common.feature
  tests/features/common/kie-controller-common.feature
  tests/features/common/kie-kieserver-common.feature
  tests/features/common/kie-workbench-authoring.feature
  tests/features/common/kie-workbench-common.feature
  tests/features/rhdm/controller/rhdm-controller.feature
  tests/features/rhdm/decisioncentral/rhdm-decisioncentral.feature
  tests/features/rhdm/kieserver/rhdm-kieserver.feature
  tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/businesscentral/rhpam-businesscentral.feature
  tests/features/rhpam/controller/rhpam-controller.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
Labels: 7.5.x ⇨ 7.5.0, ready 🚀

#332 [KIECLOUD-335] Upgrade RHDM and RHPAM cloud images to 7.5.1
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/gen_template_docs.py
Labels: 7.5.x ⇨ 7.5.1, ready 🚀

#333 [RHDM-1096] - Add missing environment variable for optaplanner
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.6.0, ready 🚀

#338 Cleanup clustering.feature tests
  tests/features/common/clustering.feature
Labels: master ⇨ 7.6.0, ready 🚀

#336 Fix controller token test
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.6.0, ready 🚀
