Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2019-07, with the labels that each got.

#276 [RHDM-1002][RHPAM-2232] Remove decisioncentral-indexing and businesscentral-indexing images and references in streams
  README.md
  jboss-kie-workbench-indexing/added/launch/configure.sh
  jboss-kie-workbench-indexing/added/launch/jboss-kie-workbench-indexing.sh
  jboss-kie-workbench-indexing/added/launch/jvm.options
  jboss-kie-workbench-indexing/added/openshift-launch.sh
  jboss-kie-workbench-indexing/configure.sh
  jboss-kie-workbench-indexing/module.yaml
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/features/common/kie-workbench-indexing.feature
  tools/build-osbs/build-osbs.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#277 [RHDM-1002][RHPAM-2232] Remove decisioncentral-indexing and businesscentral-indexing images and references in streams
  README.md
  jboss-kie-workbench-indexing/added/launch/configure.sh
  jboss-kie-workbench-indexing/added/launch/jboss-kie-workbench-indexing.sh
  jboss-kie-workbench-indexing/added/launch/jvm.options
  jboss-kie-workbench-indexing/added/openshift-launch.sh
  jboss-kie-workbench-indexing/configure.sh
  jboss-kie-workbench-indexing/module.yaml
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/features/common/kie-workbench-indexing.feature
  tools/build-osbs/build-osbs.sh
Labels: master ⇨ 7.5.0, ready 🚀

#278 [KIECLOUD-270] align whitespace output of build-overrides tool to match bot generation
  tools/build-overrides/build-overrides.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#279 [KIECLOUD-270] align whitespace output of build-overrides tool to match bot generation
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.5.0, ready 🚀

#281 [RHPAM-2002] Some external databases fail when using externaldb template
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  jboss-kie-kieserver/tests/bats/resources/timer-sql.properties
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#282 [RHPAM-2002] Some external databases fail when using externaldb template
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  jboss-kie-kieserver/tests/bats/resources/timer-sql.properties
Labels: master ⇨ 7.5.0, ready 🚀

#280 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
Labels: master ⇨ 7.5.0, ready 🚀

#283 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#284 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
Labels: master ⇨ 7.5.0, ready 🚀

#285 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#286 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#287 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
Labels: master ⇨ 7.5.0, ready 🚀

#288 [KIECLOUD-202] - Update OpenShift catalog for RHIPS/DS 6.4.12
  tools/gen-template-doc/gen_template_docs.py
  tools/gen-template-doc/template.adoc.in
Labels: master ⇨ 6.4.12, ready 🚀

#290 [KIECLOUD-277] - JMS Parameters available for user to configure but n…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#289 [KIECLOUD-277] - JMS Parameters available for user to configure but n…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
Labels: master ⇨ 7.5.0, ready 🚀

#292 [KIECLOUD-290] bump 7.4 versions to 7.4.1
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/gen_template_docs.py
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#293 Kiecloud 290 7.4.x
  tools/gen-template-doc/README.md
  tools/gen-template-doc/README_RHDM.adoc.in
  tools/gen-template-doc/README_RHPAM.adoc.in
  tools/gen-template-doc/gen_template_docs.py
  tools/gen-template-doc/release-notes-ds.adoc.in
  tools/gen-template-doc/release-notes-ips.adoc.in
  tools/gen-template-doc/release-notes-rhdm.adoc.in
  tools/gen-template-doc/template.adoc.in
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#294 [KIECLOUD-291] bring adoc generation fixes from 7.4.1 to 7.5.0
  tools/gen-template-doc/README.md
  tools/gen-template-doc/README_RHDM.adoc.in
  tools/gen-template-doc/README_RHPAM.adoc.in
  tools/gen-template-doc/gen_template_docs.py
  tools/gen-template-doc/release-notes-ds.adoc.in
  tools/gen-template-doc/release-notes-ips.adoc.in
  tools/gen-template-doc/release-notes-rhdm.adoc.in
  tools/gen-template-doc/template.adoc.in
Labels: master ⇨ 7.5.0, ready 🚀

#295 [KIECLOUD-290] bump 7.4 versions to 7.4.1
  tools/gen-template-doc/gen_template_docs.py
Labels: 7.4.x ⇨ 7.4.1, ready 🚀
