Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2019-03, with the labels that each got.

#198 [KIECLOUD-161] Update cloud images to correctly reference artifacts
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.4.0, ready 🚀

#199 [KIECLOUD-119] - Add Readme files to the Product image repositories.
  README.md
Labels: master ⇨ 7.4.0, ready 🚀

#201 [KIECLOUD-162] Prepare 6.4.x branches for modular image builds
  .github/PULL_REQUEST_TEMPLATE.md
  os.kieserver.launch/configure.sh
  os.kieserver.webapp/configure.sh
  tests/arquillian/kieserver/decisionserver64-image-stream.json
Labels: master ⇨ 6.4.11-1, ready 🚀

#168 [KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.
  jboss-kie-kieserver/added/WEB-INF/ejb-jar.xml
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/added/openshift-launch.sh
  jboss-kie-kieserver/configure.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver-jms.bats
  jboss-kie-kieserver/tests/bats/resources/META-INF/kie-server-jms.xml
  tests/bats/common/launch-common.sh
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.4.0, ready 🚀

#202 [BUILD-OVERRIDES][RHDM-864][RHPAM-1953] Upgrade RHDM and RHPAM cloud images to 7.4.0
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.4.0, ready 🚀

#185 [RHPAM-1997] PostgreSQL XA datasources does not have URL method (RHPAM-1179 follow-up)
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.4.0, ready 🚀

#203 [BUILD_OVERRIDES] 7.3.x branch copy of master branch fix
  tools/build-overrides/build-overrides.sh
Labels: 7.3.x ⇨ 7.3.1, ready 🚀

#204 [KIECLOUD-163] - Regenerate the adocs and update templates on OpenShi…
  tools/gen-template-doc/README_DS.adoc.in
  tools/gen-template-doc/README_IPS.adoc.in
  tools/gen-template-doc/gen_template_docs.py
  tools/gen-template-doc/release-notes-ds.adoc.in
  tools/gen-template-doc/release-notes-ips.adoc.in
  tools/gen-template-doc/template.adoc.in
Labels: master ⇨ 6.4.11-1, ready 🚀

#205 Fix typos
  tools/openshift-template-validator/README.md
Labels: master ⇨ 7.4.0, ready 🚀

#206 [RHPAM-640] - enable the jms signal queue in RHPAM
  jboss-kie-kieserver/added/WEB-INF/ejb-jar.xml
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver-jms.bats
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.4.0, ready 🚀
