Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2019-06, with the labels that each got.

#258 [KIECLOUD-238] - Changing log_warn signature
  tests/bats/common/logging.bash
Labels: master ⇨ 7.4.0, ready 🚀

#257 [KIECLOUD-97] - Propagate OpenShiftStartupStrategy related changes to…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-hooks.sh
Labels: master ⇨ 7.4.0, ready 🚀

#260 [KIECLOUD-97] - Propagate OpenShiftStartupStrategy related changes t…
  jboss-kie-common/added/launch/jboss-kie-common.sh
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-hooks.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver-hooks.bats
  tests/bats/common/launch-common.sh
  tools/python-mock-server/python-mock-server.py
  tools/python-mock-server/responses/bc-dc.json
  tools/python-mock-server/responses/kieserver-dc-0-replicas.json
  tools/python-mock-server/responses/kieserver-dc.json
Labels: master ⇨ 7.4.0, ready 🚀

#259 [KIECLOUD-237] Removing the need of 'secure' prefix from secured routes
  jboss-kie-common/added/launch/jboss-kie-common.sh
  jboss-kie-common/tests/bats/jboss-kie-common.bats
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
Labels: master ⇨ 7.4.0, ready 🚀

#261 [KIECLOUD-237] Fix query protocol problem (https)
  jboss-kie-common/added/launch/jboss-kie-common.sh
  jboss-kie-common/tests/bats/jboss-kie-common.bats
  jboss-kie-common/tests/bats/mock_responses/single-route.json
Labels: master ⇨ 7.4.0, ready 🚀

#262 [RHPAM-2008] HTTP 503 error is shown in Monitoring console when Kie sererver is scaled to 0
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-hooks.sh
Labels: master ⇨ 7.4.0, ready 🚀

#263 [CLOUD-3260] Maven not found in BRMS image S2I build
  os.kieserver.launch/added/kieserver-config.sh
  os.kieserver.launch/added/kieserver-install.sh
  os.kieserver.launch/added/kieserver-pull.sh
  os.kieserver.launch/added/kieserver-setup.sh
  os.kieserver.launch/added/kieserver-verify.sh
Labels: master ⇨ 6.4.12, ready 🚀

#265 [KIECLOUD-243] - Removing connection properties from XA Datasources t…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.4.0, ready 🚀

#266 [KIECLOUD-247] - Generated templates adocs files for rhpam and rhdm
  tools/gen-template-doc/gen_template_docs.py
Labels: master ⇨ 7.4.0, ready 🚀

#268 [RHDM-989][RHPAM-2210] Upgrade RHDM and RHPAM cloud images to 7.5.0
  README.md
  tests/features/common/clustering.feature
  tests/features/common/kie-common.feature
  tests/features/common/kie-controller-common.feature
  tests/features/common/kie-kieserver-common.feature
  tests/features/common/kie-workbench-authoring.feature
  tests/features/common/kie-workbench-common.feature
  tests/features/common/kie-workbench-indexing.feature
  tests/features/rhdm/controller/rhdm-controller.feature
  tests/features/rhdm/decisioncentral/rhdm-decisioncentral.feature
  tests/features/rhdm/kieserver/rhdm-kieserver.feature
  tests/features/rhdm/optaweb/optaweb.feature
  tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/businesscentral/rhpam-businesscentral.feature
  tests/features/rhpam/controller/rhpam-controller.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/gen_template_docs.py
  tools/openshift-template-validator/README.md
  tools/python-mock-server/responses/bc-dc.json
  tools/python-mock-server/responses/kieserver-dc-0-replicas.json
  tools/python-mock-server/responses/kieserver-dc.json
Labels: master ⇨ 7.5.0, ready 🚀

#270 [KIECLOUD-261] - Fixing port variable association
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
Labels: master ⇨ 7.5.0, ready 🚀

#269 [RHPAM-2217] - Removing logging import to keep the script cross compa…
  jboss-kie-common/added/launch/jboss-kie-common.sh
Labels: master ⇨ 7.5.0, ready 🚀

#272 [RHPAM-2217] - Removing logging import to keep the script cross compatible with non-EAP images (7.4.x)
  jboss-kie-common/added/launch/jboss-kie-common.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#273 [KIECLOUD-172] - Adds execute permission to hooks
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-hooks.sh
  jboss-kie-kieserver/configure.sh
Labels: master ⇨ 7.5.0, ready 🚀

#274 [KIECLOUD-172] - Adds execute permission to hooks (7.4.x)
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-hooks.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#275 [KIECLOUD-172] - Add behavior tests and correct check for execute per…
  jboss-kie-kieserver/configure.sh
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.5.0, ready 🚀
