Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2020-09, with the labels that each got.

#373 [RHPAM-2729] Provide a way to set the logging level on smartrouter image
  jboss-kie-smartrouter/added/configuration/logging.properties
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
  jboss-kie-smartrouter/configure.sh
  jboss-kie-smartrouter/tests/bats/expectations/logging-expected.properties
  jboss-kie-smartrouter/tests/bats/expectations/logging-expected_default.properties
  jboss-kie-smartrouter/tests/bats/expectations/logging-log_level_default.properties
  jboss-kie-smartrouter/tests/bats/expectations/logging-log_level_warn.properties
  jboss-kie-smartrouter/tests/bats/expectations/logging-packages_log_level_default.properties
  jboss-kie-smartrouter/tests/bats/jboss-kie-smartrouter.bats
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
Labels: master ⇨ 7.9.0, needs review :mag:

#385 [KIECLOUD-427] - Update RHPAM and RHDM repositories for 7.8.1.GA release
  tools/gen-template-doc/gen_template_docs.py
Labels: master ⇨ 7.9.0, ready 🚀

#384 [KIECLOUD-427] - Update RHPAM and RHDM repositories for 7.8.1.GA release
  tools/gen-template-doc/gen_template_docs.py
Labels: 7.8.x ⇨ 7.8.1, ready 🚀

#386 [RHPAM-3162] - WSS - Wrong URL generated in secure communication betw…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: needs review :mag:, ready 🚀

#387 [RHPAM-3162] - WSS - Wrong URL generated in secure communication betw…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: 7.8.x ⇨ 7.8.1, needs review :mag:

#388 [RHDM-1419] - Immutable KieServer fails verifying kjar if configured …
  jboss-kie-kieserver/added/launch/kieserver-verify.sh
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhdm/kieserver/rhdm-kieserver.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: master ⇨ 7.9.0, needs review :mag:
