Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2020-12, with the labels that each got.

#418 [KIECLOUD-458] - Migrate needed jboss-eap-modules from 7.3.x-legacy branch
  jboss/container/eap/s2i/bash/README.adoc
  jboss/container/eap/s2i/bash/artifacts/opt/jboss/container/eap/s2i/install-common.sh
  jboss/container/eap/s2i/bash/artifacts/opt/jboss/container/eap/s2i/s2i-core-hooks
  jboss/container/eap/s2i/bash/artifacts/usr/local/s2i/assemble
  jboss/container/eap/s2i/bash/artifacts/usr/local/s2i/run
  jboss/container/eap/s2i/bash/backward_compatibility.sh
  jboss/container/eap/s2i/bash/configure.sh
  jboss/container/eap/s2i/bash/module.yaml
Labels: master ⇨ 7.10.0, needs review :mag:

#420 [RHPAM-3326] - Defaul value for MaxMetaspaceSize in Operator overried…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: needs review :mag:

#421 [KIECLOUD - 479] - Updated EJB Timer related env vars to have same pattern
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
Labels: needs review :mag:

#414 [KIECLOUD-480] - Allowing value flag as "optional" for LdapExtended login module
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-security-login-modules.sh
  jboss-kie-wildfly-common/module.yaml
  jboss-kie-wildfly-common/tests/bats/expectations/standalone-openshift-ldap-all.xml
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-security-ldap.bats
  tests/features/common/kie-common.feature
Labels: needs review :mag:

#424 [BXMSDOC-5817] - Small improvement request for ADOC generation: bulle…
  tools/gen-template-doc/gen_template_docs.py
Labels: master ⇨ 7.10.0, ready 🚀
