Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2020-11, with the labels that each got.

#400 Add Kaitou to default reviewers
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#397 [7.9.X][RHPAM-3141] - Move index files (org.uberfire.metadata.index.dir) fro…
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-common.feature
Labels: needs review :mag:, on hold ⏳

#398 [RHPAM-3211] Openshift properties related to passwords in EJB_TIMER cannot use literal $n
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: needs review :mag:

#401 [AF-2626] - Create Dashbuilder Runtime Image
  .circleci/config.yml
  jboss-eap-config-openshift/16.0-openjdk11/module.yaml
  jboss-kie-common-dependencies/module.yaml
  jboss-kie-dashbuilder/added/launch/jboss-kie-dashbuilder.sh
  jboss-kie-dashbuilder/added/openshift-launch.sh
  jboss-kie-dashbuilder/configure.sh
  jboss-kie-dashbuilder/module.yaml
  jboss-kie-dashbuilder/tests/bats/jboss-kie-dashbuilder.bats
  jboss-kie-dashbuilder/tests/bats/props/dashbuilder-dataset.properties
  jboss-kie-dashbuilder/tests/bats/props/dashbuilder-server-template.properties
  jboss-kie-dashbuilder/tests/bats/props/dashbuilder.properties
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-common.sh
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss/container/eap/prometheus/agent/module.yaml
  jboss/container/eap/prometheus/config/7.2/module.yaml
  os-eap-legacy/os-eap7-launch/module.yaml
  tests/features/common/kie-common.feature
  tests/features/common/kie-controller-common.feature
  tests/features/common/kie-kieserver-common.feature
  tests/features/common/kie-workbench-common.feature
  tests/features/rhdm/rhdm-controller.feature
  tests/features/rhdm/rhdm-decisioncentral.feature
  tests/features/rhdm/rhdm-kieserver.feature
  tests/features/rhpam/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/rhpam-businesscentral.feature
  tests/features/rhpam/rhpam-controller.feature
  tests/features/rhpam/rhpam-dashbuilder.feature
  tests/features/rhpam/rhpam-kieserver.feature
  tests/features/rhpam/rhpam-process-migration.feature
  tests/features/rhpam/rhpam-smartrouter.feature
Labels: master ⇨ 7.10.0, needs review :mag:, ready 🚀

#405 [RHPAM-3299] - BC image not using PV to store its local .m2/repository
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/added/openshift-launch.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-authoring.feature
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#404 [RHPAM-3299] - BC image not using PV to store its local .m2/repository
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/added/openshift-launch.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-authoring.feature
Labels: master ⇨ 7.10.0, ready 🚀

#409 [RHPAM-3300] - Add EJB timer related settings in OCP to avoid duplica…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/rhpam-kieserver.feature
Labels: master ⇨ 7.10.0, ready 🚀

#408 [RHPAM-3300] - Add EJB timer related settings in OCP to avoid duplica…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#406 [KIECLOUD-453] - Adapt product artifacts definitions to CPaaS build
  tools/build-overrides/build-overrides.sh
Labels: master ⇨ 7.10.0, ready 🚀

#407 [KIECLOUD-453] - Adapt product artifacts definitions to CPaaS build
  tools/build-overrides/build-overrides.sh
Labels: 7.9.x ⇨ 7.9.1, needs review :mag:

#411 [KIECLOUD-464] - Fix smartrouter logger configuration test
  tests/features/rhpam/rhpam-smartrouter.feature
Labels: master ⇨ 7.10.0, ready 🚀

#410 [KIECLOUD-464] - Fix smartrouter logger configuration test
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#413 [RHPAM-3300] - Add EJB timer related settings in OCP to avoid duplica…
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#412 [RHPAM-3300] - Add EJB timer related settings in OCP to avoid duplicate timer execution
  tests/features/rhpam/rhpam-kieserver.feature
Labels: master ⇨ 7.10.0, ready 🚀

#415 [KIECLOUD-467] - Prepare RHDM and RHPAM 7.9.x branches for 7.9.1 release
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/gen_template_docs.py
Labels: 7.9.x ⇨ 7.9.1, needs review :mag:
