Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2020-10, with the labels that each got.

#390 [KIECLOUD-446] - Prepare RHPAM and RHDM master branch for next release
  tests/features/rhdm/controller/rhdm-controller.feature
  tests/features/rhdm/decisioncentral/rhdm-decisioncentral.feature
  tests/features/rhdm/kieserver/rhdm-kieserver.feature
  tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/businesscentral/rhpam-businesscentral.feature
  tests/features/rhpam/controller/rhpam-controller.feature
  tests/features/rhpam/kieserver/rhpam-kieserver.feature
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/README_RHDM.adoc.in
  tools/gen-template-doc/README_RHPAM.adoc.in
  tools/gen-template-doc/gen_template_docs.py
Labels: master ⇨ 7.10.0, ready 🚀

#391 [KIECLOUD-452] - Move behave tests from rhpam/dm-7-image repository t…
  tests/features/common/kie-controller-common.feature
  tests/features/common/kie-kieserver-common.feature
  tests/features/common/kie-workbench-common.feature
  tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/process-migration/process-migration.feature
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
Labels: master ⇨ 7.10.0, needs review :mag:

#392 [RHPAM-3141] - Move index files (org.uberfire.metadata.index.dir) fro…
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-common.feature
Labels: needs review :mag:

#395 [7.9.x][RHPAM-3141] - Move index files (org.uberfire.metadata.index.dir) fro…
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-common.feature
Labels: needs review :mag:

#396 Revert "[7.9.x][RHPAM-3141] - Move index files (org.uberfire.metadata.index.dir) fro…"
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-common.feature
Labels: needs review :mag:
