Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2020-01, with the labels that each got.

#341 [RHPAM-2548] - quickstart hello-rules-multi-module is not working wit…
  jboss-kie-kieserver/added/launch/kieserver-install.sh
Labels: master ⇨ 7.7.0, ready 🚀

#342 [RHPAM-2548] - quickstart hello-rules-multi-module is not working wit…
  jboss-kie-kieserver/added/launch/kieserver-install.sh
Labels: 7.6.x ⇨ 7.6.0, ready 🚀

#347 [KIECLOUD-352] - Smartrouter is not honoring JAVA_OPTS_APPEND and dyn…
  jboss-kie-smartrouter/added/openshift-launch.sh
Labels: master ⇨ 7.7.0

#348 [RHPAM-2175] Use only adminUser in all the scripts
  jboss-kie-controller/added/launch/jboss-kie-controller.sh
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-smartrouter/added/launch/jboss-kie-smartrouter.sh
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-security.sh
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/features/common/kie-controller-common.feature
  tests/features/common/kie-kieserver-common.feature
  tests/features/common/kie-workbench-common.feature
  tests/features/rhdm/decisioncentral/rhdm-decisioncentral.feature
  tests/features/rhpam/businesscentral-monitoring/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/businesscentral/rhpam-businesscentral.feature
  tests/features/rhpam/controller/rhpam-controller.feature
  tests/features/rhpam/smartrouter/rhpam-smartrouter.feature
  tools/python-mock-server/responses/bc-dc.json
  tools/python-mock-server/responses/kieserver-dc-0-replicas.json
  tools/python-mock-server/responses/kieserver-dc.json
Labels: master ⇨ 7.7.0, ready 🚀

#350 [RHPAM-2260] - Remove MSSQL externaldb ejb3 timer SQL workaround
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
Labels: master ⇨ 7.7.0, ready 🚀
