Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2021-03, with the labels that each got.

#419 [RHPAM-3181] Update the openshift.PING to kubernetes.PING
  jboss-kie-wildfly-common/tests/bats/expectations/formatter/standalone-expected.xml
  jboss-kie-wildfly-common/tests/bats/expectations/formatter/standalone-unformatted.xml
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/features/common/clustering.feature
  tools/gen-template-doc/template.adoc.in
Labels: master ⇨ 7.11.0, needs review :mag:

#437 [RHDM-1450] Update the openshift.PING to kubernetes.PING
  tests/features/common/clustering.feature
Labels: needs review :mag:

#438 [RHPAM-3494] - Make pulling of dependencies and kjar validation skipp…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/added/launch/kieserver-env.sh
  jboss-kie-kieserver/added/launch/kieserver-pull.sh
  jboss-kie-kieserver/added/launch/kieserver-verify.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  jboss-kie-kieserver/tests/bats/kieserver-install.bats
  jboss-kie-kieserver/tests/bats/kieserver-pull.bats
  jboss-kie-kieserver/tests/bats/kieserver-verify.bats
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.11.0, ready 🚀

#439 [RHPAM-3494] - Make pulling of dependencies and kjar validation skipp…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/added/launch/kieserver-env.sh
  jboss-kie-kieserver/added/launch/kieserver-pull.sh
  jboss-kie-kieserver/added/launch/kieserver-verify.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  jboss-kie-kieserver/tests/bats/kieserver-install.bats
  jboss-kie-kieserver/tests/bats/kieserver-pull.bats
  jboss-kie-kieserver/tests/bats/kieserver-verify.bats
  tests/features/common/kie-kieserver-common.feature
Labels: 7.10.x ⇨ 7.10.1, ready 🚀

#440 [RHPAM - 3499] - [ONE-OFF](7.9.1) Make pulling of dependencies and kjar
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/added/launch/kieserver-env.sh
  jboss-kie-kieserver/added/launch/kieserver-pull.sh
  jboss-kie-kieserver/added/launch/kieserver-verify.sh
  jboss-kie-kieserver/tests/bats/kieserver-install.bats
  jboss-kie-kieserver/tests/bats/kieserver-pull.bats
  jboss-kie-kieserver/tests/bats/kieserver-verify.bats
  tests/features/common/kie-kieserver-common.feature
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#442 [RHPAM-3506] - /opt/eap/bin/launch/messaging.sh No such file or direc…
  jboss-kie-controller/added/openshift-launch.sh
  jboss-kie-dashbuilder/added/openshift-launch.sh
  jboss-kie-kieserver/added/openshift-launch.sh
  jboss-kie-workbench/added/openshift-launch.sh
  os-eap-legacy/os-eap7-launch/added/launch/openshift-common.sh
Labels: master ⇨ 7.11.0, ready 🚀

#443 [KIECLOUD-508] - Prepare RHDM and RHPAM 7.10.x branches for 7.10.1 re…
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/gen_template_docs.py
Labels: 7.10.x ⇨ 7.10.1, ready 🚀

#444 [KIECLOUD-508] - Prepare RHDM and RHPAM 7.10.x branches for 7.10.1 re…
  tools/gen-template-doc/gen_template_docs.py
Labels: master ⇨ 7.11.0, ready 🚀

#445 [KIECLOUD-506] - Update the jboss-kie-modules README file to reflect …
  README.md
Labels: master ⇨ 7.11.0, ready 🚀

#447 [KIECLOUD-518] - Update RHSSO EAP adatpers from 7.3.1 to 7.4.5
  os-eap7-sso-adapters/configure.sh
  os-eap7-sso-adapters/module.yaml
Labels: master ⇨ 7.11.0, needs review :mag:

#434 [RHPAM-3330] Operator/Image support for Kie-Server Cluster support
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.11.0, ready 🚀

#446 [RHPAM-3331] Operator for AMQ Streams (Kafka) integration
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.11.0, ready 🚀

#448 [KIECLOUD-520] - Update prometheus-jmx-exporter to jmx_prometheus_jav…
  tests/features/common/kie-common.feature
Labels: needs review :mag:
