Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2021-07, with the labels that each got.

#460 [RHPAM-3640] Configure Kafka JBPM Emitter from Operator -7.11.x
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/configure.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: 7.11.x ⇨ 7.11.1, ready 🚀

#456 [RHPAM-3640] Configure Kafka JBPM Emitter from Operator
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/configure.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.12.0, ready 🚀

#471 [KIECLOUD-551] - Prepare RHPAM and RHDM for 7.11.1 release
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/gen_template_docs.py
Labels: 7.11.x ⇨ 7.11.1, needs review :mag:

#472 [KIECLOUD-554] - Fix jBPM kafka emitter integration
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhpam/rhpam-kieserver.feature
Labels: main ⇨ 7.12.0, ready 🚀

#473 [KIECLOUD-554] - Fix jBPM kafka emitter integration (#472)
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhpam/rhpam-kieserver.feature
Labels: 7.11.x ⇨ 7.11.1, needs review :mag:

#474 [KIECLOUD-550] - Adjust permissions on os-eap7-openshift module
  os-eap-legacy/os-eap7-openshift/prepare.sh
Labels: main ⇨ 7.12.0

#475 [KIECLOUD-549] - Adjust permissions on rhpam/dm-7-kieserver module
  jboss-kie-kieserver/configure.sh
Labels: main ⇨ 7.12.0, ready 🚀

#476 [KIECLOUD-548] - Adjust permissions on os-eap-sso-adapters module
  os-eap7-sso-adapters/configure.sh
Labels: main ⇨ 7.12.0, ready 🚀

#477 [KIECLOUD-556] - Adjust permissions on rhpam/dm base module workbench
  jboss-kie-kieserver/configure.sh
  jboss-kie-workbench/configure.sh
  os-eap-legacy/os-eap7-openshift/prepare.sh
Labels: main ⇨ 7.12.0, ready 🚀

#478 [RHPAM-3594] - Allow disabling of Kie server embedded healthcheck
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-authoring.feature
Labels: main ⇨ 7.12.0, ready 🚀

#479 [KIECLOUD-558] - Adjust permissions on rhpam/dm base module controller
  jboss-kie-controller/configure.sh
Labels: main ⇨ 7.12.0, ready 🚀

#480 [RHPAM-3805] - Missing kie dependencies in Kie Server ocp image
  jboss-kie-kieserver/configure.sh
Labels: 7.11.x ⇨ 7.11.1, ready 🚀

#481 [KIECLOUD-566] - Permission issues on standalone dir on workbench and…
  jboss-kie-dashbuilder/configure.sh
  jboss-kie-workbench/configure.sh
Labels: main ⇨ 7.12.0, needs review :mag:
