Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2021-01, with the labels that each got.

#422 [RHPAM-3248] - Provision Dashbuilder image with operator
  jboss-kie-dashbuilder/added/launch/jboss-kie-dashbuilder.sh
  jboss-kie-dashbuilder/configure.sh
  jboss-kie-dashbuilder/tests/bats/jboss-kie-dashbuilder.bats
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/rhpam/rhpam-dashbuilder.feature
Labels: master ⇨ 7.10.0, ready 🚀

#423 [RHPAM-3364] BusinessCentral pod in authoring-ha deployment won't start with EAP_734_CR2
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
Labels: master ⇨ 7.10.0, needs review :mag:

#426 [KIECLOUD-487] - Prepare RHPAM and RHDM repositories for next version…
  tests/features/rhdm/rhdm-controller.feature
  tests/features/rhdm/rhdm-decisioncentral.feature
  tests/features/rhdm/rhdm-kieserver.feature
  tests/features/rhpam/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/rhpam-businesscentral.feature
  tests/features/rhpam/rhpam-controller.feature
  tests/features/rhpam/rhpam-dashbuilder.feature
  tests/features/rhpam/rhpam-kieserver.feature
  tests/features/rhpam/rhpam-smartrouter.feature
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/README_RHDM.adoc.in
  tools/gen-template-doc/README_RHPAM.adoc.in
Labels: master ⇨ 7.11.0, needs review :mag:

#425 [KIECLOUD-448] - Provide automated way to update product version on R…
  tools/gen-template-doc/gen_template_docs.py
  tools/update-version/update-version.py
Labels: master ⇨ 7.11.0, ready 🚀

#430 [KIECLOUD-491] - Fix existing behave tests
  tests/features/common/kie-common.feature
Labels: 7.10.x ⇨ 7.10.0, ready 🚀

#429 [KIECLOUD-491] - Fix existing behave tests
  tests/features/common/kie-common.feature
Labels: master ⇨ 7.11.0, ready 🚀

#427 [RHDM-1567] - LDAP sync issues when AUTH_LDAP_BASE_FILTER contains th…
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-security-login-modules.sh
  jboss-kie-wildfly-common/tests/bats/expectations/standalone-openshift-ldap-baseFilter.xml
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-security-ldap.bats
  tests/features/common/kie-common.feature
Labels: master ⇨ 7.11.0, ready 🚀
