Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2021-04, with the labels that each got.

#450 update reviewers
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#449 [RHPAM-3517] - java.lang.ClassNotFoundException: org.apache.maven.mod…
  jboss-kie-db-drivers/configure.sh
  jboss-kie-db-drivers/module.yaml
  jboss-kie-jdk-clean/module.yaml
  tests/features/common/kie-common.feature
  tests/features/common/kie-controller-common.feature
  tests/features/common/kie-kieserver-common.feature
  tests/features/common/kie-workbench-common.feature
  tests/features/rhdm/rhdm-kieserver.feature
  tests/features/rhpam/rhpam-kieserver.feature
  tests/features/rhpam/rhpam-smartrouter.feature
Labels: master ⇨ 7.11.0, ready 🚀

#452 Prepare master branch of all image repositories for 7.12 release
  tests/features/rhdm/rhdm-controller.feature
  tests/features/rhdm/rhdm-decisioncentral.feature
  tests/features/rhdm/rhdm-kieserver.feature
  tests/features/rhpam/rhpam-businesscentral-monitoring.feature
  tests/features/rhpam/rhpam-businesscentral.feature
  tests/features/rhpam/rhpam-controller.feature
  tests/features/rhpam/rhpam-dashbuilder.feature
  tests/features/rhpam/rhpam-kieserver.feature
  tests/features/rhpam/rhpam-smartrouter.feature
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/README_RHDM.adoc.in
  tools/gen-template-doc/README_RHPAM.adoc.in
  tools/gen-template-doc/gen_template_docs.py
Labels: needs review :mag:

#453 [RHPAM-3628]Kafka capability is not correctly set up for Kie Server image
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: 7.11.x ⇨ 7.11.0, ready 🚀

#454 [RHPAM-3628]Kafka capability is not correctly set up for Kie Server image
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.12.0, ready 🚀

#451 [RHPAM-2855] - Broken symlink in registry.redhat.io/rhpam-7/rhpam-kie…
  tests/features/common/kie-kieserver-common.feature
Labels: master ⇨ 7.12.0, ready 🚀
