Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2021-11, with the labels that each got.

#493 [RHPAM-3808] - jdbcURL Oracle with multiple database url connection g…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/rhpam-kieserver.feature
Labels: ready 🚀, needs review :mag:, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#500 [KIECLOUD-544] - Combine the prometheus agent and config modules
  jboss/container/eap/prometheus/agent/configure.sh
  jboss/container/eap/prometheus/agent/module.yaml
  jboss/container/eap/prometheus/agent/src/standalone.conf
  jboss/container/eap/prometheus/config/7.4/README.adoc
  jboss/container/eap/prometheus/config/7.4/artifacts/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml
  jboss/container/eap/prometheus/config/7.4/configure.sh
  jboss/container/eap/prometheus/config/7.4/module.yaml
  jboss/container/eap/prometheus/config/7.4/src/standalone.conf
Labels: needs review :mag:, needs-cherry-pick :cherries:

#499 [KIECLOUD-594] Migrate the access_log_valve script to wildfly-cekit-modules
  os-eap-legacy/os-eap-launch/added/launch/access_log_valve.sh
  tests/features/common/kie-kieserver-common.feature
Labels: needs review :mag:, main ⇨ 7.13.0

#502 [KIECLOUD-505] Update https.sh script to use the one provided by wildfly-cekit-modules
  os-eap-legacy/os-eap7-launch/added/launch/https.sh
  tests/features/common/kie-controller-common.feature
Labels: ready 🚀, main ⇨ 7.13.0
