Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2021-06, with the labels that each got.

#461 [KIECLOUD-542] Conscious Language on KieCloud repos
  README.md
  jboss-kie-smartrouter/added/openshift-launch.sh
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  tests/bats/common/launch-common.sh
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhdm/rhdm-kieserver.feature
  tests/features/rhpam/rhpam-kieserver.feature
  tools/gen-template-doc/README.md
  tools/gen-template-doc/gen_template_docs.py
  tools/gen-template-doc/release-notes-ds.adoc.in
  tools/gen-template-doc/release-notes-ips.adoc.in
Labels: needs review :mag:

#464 [KIECLOUD-530] -hostname package is being installed by two different …
  os-eap-legacy/os-eap-launch/module.yaml
Labels: master ⇨ 7.12.0, needs review :mag:

#465 [KIECLOUD-530] -hostname package is being installed by two different …
  os-eap-legacy/os-eap-launch/module.yaml
Labels: 7.11.x ⇨ 7.11.1, needs review :mag:

#462 [KIECLOUD-510] - Remove the json_logging.sh script from jboss-kie-mod…
  os-eap-legacy/os-eap7-launch/added/launch/json_logging.sh
Labels: master ⇨ 7.12.0, needs review :mag:

#463 [KIECLOUD-510] - Remove the json_logging.sh script from jboss-kie-mod…
  os-eap-legacy/os-eap7-launch/added/launch/json_logging.sh
Labels: 7.11.x ⇨ 7.11.1, needs review :mag:

#467 [KIECLOUD-532] JDBC driver on RHDM/RHPAM images
  jboss-kie-controller/configure.sh
  jboss-kie-kieserver/configure.sh
  jboss-kie-workbench/configure.sh
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhpam/rhpam-kieserver.feature
Labels: master ⇨ 7.12.0, ready 🚀

#468 [KIECLOUD-532] JDBC driver on RHDM/RHPAM images (#467)
  jboss-kie-controller/configure.sh
  jboss-kie-kieserver/configure.sh
  jboss-kie-workbench/configure.sh
  tests/features/common/kie-kieserver-common.feature
  tests/features/rhpam/rhpam-kieserver.feature
Labels: 7.11.x ⇨ 7.11.1

#470 [RHPAM-3761] - Token based auth not working in business central monit…
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-common.feature
Labels: 7.11.x ⇨ 7.11.1, ready 🚀

#469 [RHPAM-3761] - Token based auth not working in business central monit…
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-common.feature
Labels: master ⇨ 7.12.0, ready 🚀
