Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2022-01, with the labels that each got.

#513 [KIECLOUD-597] - XA datasource URL property is set even if no URL is …
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/rhpam-kieserver.feature
Labels: ready 🚀, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#515 Updated Reviewers file to include davidesalerno
  .github/bot-files/reviewers.yml
Labels: ready 🚀

#518 [RHPAM-3525] - Logger configurations in OCP
  jboss-eap-config-openshift/EAP7.4.0/added/standalone-openshift.xml
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-common.sh
  jboss-kie-wildfly-common/module.yaml
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-common.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#517 [KIECLOUD-592] Remove domain mode and not needed files from JBoss EAP…
  jboss-kie-wildfly-common/configure.sh
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-common.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, main ⇨ 7.13.0

#503 [KIECLOUD-594] 7.12.x Migrate the access_log_valve script to wildfly-cekit-modules
  os-eap-legacy/os-eap-launch/added/launch/access_log_valve.sh
  tests/features/common/kie-kieserver-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1

#516 [RHPAM-3525] - Logger configurations in OCP
  jboss-eap-config-openshift/EAP7.4.0/added/standalone-openshift.xml
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-common.sh
  jboss-kie-wildfly-common/module.yaml
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-common.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1, needs-cherry-pick :cherries:

#501 [KIECLOUD-544] - Combine the prometheus agent and config modules
  jboss/container/eap/prometheus/agent/configure.sh
  jboss/container/eap/prometheus/agent/module.yaml
  jboss/container/eap/prometheus/agent/src/standalone.conf
  jboss/container/eap/prometheus/config/7.4/README.adoc
  jboss/container/eap/prometheus/config/7.4/artifacts/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml
  jboss/container/eap/prometheus/config/7.4/configure.sh
  jboss/container/eap/prometheus/config/7.4/module.yaml
  jboss/container/eap/prometheus/config/7.4/src/standalone.conf
Labels: ready 🚀, 7.12.x ⇨ 7.12.1

#497 [RHPAM-3808] - jdbcURL Oracle with multiple database url connection g…
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/rhpam-kieserver.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1

#514 [KIECLOUD-597] - XA datasource URL property is set even if no URL is …
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/rhpam-kieserver.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1, cherry-pick :cherries:

#496 [RHPAM-3528-7.12.x] Increase KieExecutorMDB threads in RHPAM image
  jboss-eap-config-openshift/EAP7.4.0/added/standalone-openshift.xml
  jboss-kie-kieserver/added/WEB-INF/ejb-jar.xml
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver-jms.bats
  tests/features/common/kie-kieserver-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1

#505 [KIECLOUD-505] 7.12.x Update https.sh script to use the one provided by wild…
  os-eap-legacy/os-eap7-launch/added/launch/https.sh
  tests/features/common/kie-controller-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1
