Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2022-03, with the labels that each got.

#534 [RHPAM-4198] - KieApp deployment with LDAP integration fails when bin…
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-elytron.sh
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-elytron.bats
  tests/features/common/kie-common.feature
  tests/features/common/kie-kieserver-common.feature
Labels: ready 🚀, main ⇨ 7.13.0

#540 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image
  jboss-eap-config-openshift/EAP7.4.0/added/standalone-openshift.xml
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver-jms.bats
  tests/features/common/kie-kieserver-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1, needs-cherry-pick :cherries:

#541 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image (#540)
  jboss-eap-config-openshift/EAP7.4.0/added/standalone-openshift.xml
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver-jms.bats
  tests/features/common/kie-kieserver-common.feature
Labels: needs review :mag:, main ⇨ 7.13.0

#538 RHPAM-3512 - Include missing maven goals on the kieserver-pull.sh script
  jboss-kie-kieserver/added/launch/kieserver-pull.sh
Labels: ready 🚀, main ⇨ 7.13.0

#542 [RHPAM-4148] - LDAP authentication fails because direct-verification=…
  jboss-kie-wildfly-common/module.yaml
Labels: ready 🚀, main ⇨ 7.13.0

#543 [RHPAM-4194] - missing support of KIE_SERVER_BYPASS_AUTH_USER environ…
  jboss-kie-workbench/added/launch/jboss-kie-workbench.sh
  jboss-kie-workbench/tests/bats/jboss-kie-workbench.bats
  tests/features/common/kie-workbench-common.feature
Labels: needs review :mag:, main ⇨ 7.13.0
