Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2022-02, with the labels that each got.

#521 [RHPAM-4132] - OpenShift images ignore LDAP roles when is set defautl…
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-elytron.sh
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-elytron.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1, cherry-pick :cherries:

#520 [RHPAM-4132] - OpenShift images ignore LDAP roles when is set defautl…
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-elytron.sh
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-elytron.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#522 [KIECLOUD-592] Remove domain mode and not needed files from JBoss EAP…
  jboss-kie-wildfly-common/configure.sh
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-common.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, main ⇨ 7.13.0

#519 [KIECLOUD-598] - Not able to configure datasources URLs with parameters
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/rhpam-kieserver.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1, needs-cherry-pick :cherries:

#524 [KIECLOUD-598] - Not able to configure datasources URLs with parameters
  jboss-kie-kieserver/added/launch/jboss-kie-kieserver.sh
  jboss-kie-kieserver/tests/bats/jboss-kie-kieserver.bats
  tests/features/rhpam/rhpam-kieserver.feature
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#526 [RHPAM-3525] - Logger configurations in OCP
  tests/features/common/kie-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1, needs-cherry-pick :cherries:

#527 [RHPAM-3525] - Logger configurations in OCP
  tests/features/common/kie-common.feature
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#523 [RHPAM-4146] - [ELYTRON] Authorization fails when using role mapping
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-elytron.sh
  jboss-kie-wildfly-common/module.yaml
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-elytron.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#528 [RHPAM-4146] - [ELYTRON] Authorization fails when using role mapping
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-elytron.sh
  jboss-kie-wildfly-common/module.yaml
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-elytron.bats
  tests/features/common/kie-common.feature
Labels: ready 🚀, 7.12.x ⇨ 7.12.1, cherry-pick :cherries:
