Repository jboss-container-images/jboss-kie-modules, pull requests merged in 2022-12, with the labels that each got.

#551 [RHPAM-3079] - update maven to 3.8
  jboss-kie-jdk-clean/configure.sh
  jboss-kie-jdk-clean/module.yaml
  tests/features/common/kie-common.feature
Labels: needs review :mag:

#555 [RHPAM-4529] - Allowing special characters for passwords in BC operator
  jboss-kie-wildfly-common/added/launch/jboss-kie-wildfly-elytron.sh
  jboss-kie-wildfly-common/tests/bats/jboss-kie-wildfly-elytron.bats
  tests/bats/common/launch-common.sh
  tests/bats/common/log_utils.bash
  tests/bats/common/logging.bash
  tests/bats/common/openshift-node-name.sh
  tests/bats/common/xml_utils.bash
  tests/features/common/kie-common.feature
Labels: ready 🚀, 7.13.x ⇨ 7.13.2, needs-cherry-pick :cherries:

#552 [KIECLOUD-656] - Prepare RHPAM branches for 7.13.2
  tools/build-overrides/build-overrides.sh
  tools/gen-template-doc/gen_template_docs.py
  tools/update-version/update-version.py
Labels: needs review :mag:, 7.13.x ⇨ 7.13.2

#553 [KIECLOUD-656] - Prepare BAMOE branches for 8.0.2
  tools/update-version/update-version.py
Labels: needs review :mag:

#557 [KIECLOUD-672] add pkg-update module
  jobss-kie-pkg-update/configure
  jobss-kie-pkg-update/module.yaml
Labels: ready 🚀, main ⇨ 7.14.0

#558 [7.13.x-blue][KIECLOUD-672] add pkg-update module
  jobss-kie-pkg-update/configure
  jobss-kie-pkg-update/module.yaml
Labels: ready 🚀

#559 [7.13.x][KIECLOUD-672] add pkg-update module
  jobss-kie-pkg-update/configure
  jobss-kie-pkg-update/module.yaml
Labels: 7.13.x ⇨ 7.13.2

#563 [KIECLOUD-665] - Fix existing pipelines for RHPAM images
  tools/build-osbs/build-osbs.sh
  tools/build-overrides/build-overrides.sh
Labels: needs-cherry-pick :cherries:

#564 [KIECLOUD-665] - Fix existing pipelines for RHPAM images
  tools/build-osbs/build-osbs.sh
  tools/build-overrides/build-overrides.sh
Labels: needs review :mag:, 7.13.x ⇨ 7.13.2, cherry-pick :cherries:

#565 [KIECLOUD-665] - Fix existing pipelines for RHPAM images
  tools/build-osbs/build-osbs.sh
  tools/build-overrides/build-overrides.sh
Labels: needs review :mag:, 7.13.x ⇨ 7.13.2, cherry-pick :cherries:

#566 [KIECLOUD-665] - Fix existing pipelines for RHPAM images
  tools/build-osbs/build-osbs.sh
Labels: needs review :mag:, needs-cherry-pick :cherries:, main ⇨ 7.14.0

#567 [KIECLOUD-665] - Fix existing pipelines for RHPAM images
  tools/build-osbs/build-osbs.sh
Labels: needs review :mag:, 7.13.x ⇨ 7.13.2, cherry-pick :cherries:

#568 [KIECLOUD-665] - Fix existing pipelines for RHPAM images
  tools/build-osbs/build-osbs.sh
Labels: needs review :mag:, cherry-pick :cherries:

#569 [KIECLOUD-665] - few tweaks
  tools/build-osbs/build-osbs.sh
Labels: needs review :mag:

#570 [KIECLOUD-665] - few tweaks
  tools/build-osbs/build-osbs.sh
Labels: needs review :mag:

#579 [KIECLOUD-665] - Fix existing pipelines for RHPAM images, small tweaks
  tools/build-osbs/build-osbs.sh
Labels: needs review :mag:

#572 [KIECLOUD-671] - Refactor kie-common.feature tests
  tests/features/common/kie-common.feature
  tests/features/common/kie-maven-common.feature
  tests/features/common/kie-security-common.feature
Labels: needs review :mag:, needs-cherry-pick :cherries:, main ⇨ 7.14.0

#573 [KIECLOUD-671] - Refactor kie-common.feature tests
  tests/features/common/kie-common.feature
  tests/features/common/kie-maven-common.feature
  tests/features/common/kie-security-common.feature
Labels: needs review :mag:, 7.13.x ⇨ 7.13.2, cherry-pick :cherries:

#574 [KIECLOUD-671] - Refactor kie-common.feature tests
  tests/features/common/kie-common.feature
  tests/features/common/kie-maven-common.feature
  tests/features/common/kie-security-common.feature
Labels: needs review :mag:, cherry-pick :cherries:
